- id: md2po
  name: md2po
  entry: md2po -sq
  description: Utility like xgettext to extract Markdown content dumping it inside PO files
  language: python
- id: md2po2md
  name: md2po2md
  entry: md2po2md
  description: Translates Markdown files using PO files for a set of predefined language codes creating multiple directories, one for each language
  language: python
