version: 2
formats: all

sphinx:
  fail_on_warning: true
  configuration: docs/conf.py

build:
  os: ubuntu-20.04
  tools:
    python: '3.10'
  jobs:
    pre_create_environment:
      - asdf plugin add poetry
      - asdf install poetry latest
      - asdf global poetry latest
      - poetry config virtualenvs.create false
    post_install:
      - poetry install --with doc
