version: 2
formats: all

sphinx:
  fail_on_warning: true
  configuration: docs/conf.py

python:
  version: '3.8'
  install:
    - method: pip
      path: .
      extra_requirements:
        - doc
  system_packages: true
