version: 2
formats: all

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true

build:
  os: ubuntu-20.04
  tools:
    python: '3.10'
  jobs:
    post_install:
      - pip install poetry==1.2.0b1
      - poetry config virtualenvs.create false
      - poetry install --only default,doc
