name: Update copyright years

permissions:
  pull-requests: write
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: 0 3 2 1 *

jobs:
  update-license-year:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - uses: FantasticFiasco/action-update-license-year@v3.0.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
